create desktop version for personal portfolio
bengigo/micronaut-portfolio pull request #5
Opened 2022-02-25 09:38 UTC by bengigo

changes made in this branch:

- create desktop elements that aren't available for mobile

- using media queries; hide mobile element, hide desktop element, style desktop elements

2022-02-25 14:05 UTC, BenMukebo requested changes
### Hi **@bengigo**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Good commit messages ✔️ 
- Descriptive README file.  ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-25 14:05 UTC, BenMukebo commented on styles.css
> +    width: 1440px;
- [ ] Kindly don't specify any max-width as this desktop version is the last size you are working on, you can keep it and set the max-width to a value higher than this but I would suggest you remove it  since it will cause some misbehavior on different screens, see this image below, when I resize over the max-width, the media query is not recognized at all, Please fix that
- [ ] 
<img width="939" alt="see this" src="https://user-images.githubusercontent.com/79058364/155727645-2b738e21-3428-4a60-b123-081b2e18609d.png">

2022-02-26 11:06 UTC, medaminedev66 requested changes
Hi @bengigo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

- [ ] Your page is scrolling horizontally. Kindly fix the width issue of your page in the desktop version and make sure that there is no horizontal scroll bar at the bottom of your page:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/77190203/155840668-b68d0cd1-7638-4d91-8015-4892631b6339.png">



_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-26 13:51 UTC, prolajumokeoni approved these changes
Hi @bengigo 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Suggested changes
_Check the comments under the review.



![approved-stamp](https://user-images.githubusercontent.com/69638013/155845627-c70fb6a0-a62f-4d3b-89e9-39f41a53c526.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-26 13:51 UTC, prolajumokeoni commented on index.html
> +      </p>
## OPTIONAL 

- [ ] Good job adding this text, just as the previous reviewer requested, kindly add styling to this text  so it looks like the original design 👍🏿
 


 Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![tezzxt](https://user-images.githubusercontent.com/69638013/155845435-3bbf13d7-724f-46f0-9848-d44895c3a705.PNG) |  ![image](https://user-images.githubusercontent.com/69638013/155845546-ca9c59a0-381c-4ccd-944f-6d8189d72b03.png)

2022-02-26 13:58 UTC, merged